-- Database: GLOBALVSF Metadata version: 2 Exported: Jan 31, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "ZZ_PTO_DELETED" USING 'ZZ_PTO_DELETED.mkd' PAGESIZE=4096 (
 "EMPLOYEE" CHAR(5) NOT NULL,
 "NAME" CHAR(100) NOT NULL,
 "AVAILABLE" DOUBLE NOT NULL,
 "SUP_ID" CHAR(5) NOT NULL,
 "SUPERVSR" CHAR(100) NOT NULL,
 "PAY_TYPE" CHAR(1) NOT NULL,
 "HIRE_DATE" DATE NOT NULL,
 "PTO_STEP_DATE" DATE NOT NULL,
 "PTO_STEP" INTEGER NOT NULL,
 "DELETE_REASON" CHAR(200) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
