-- Database: GLOBALVSF Metadata version: 2 Exported: Jan 31, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "ZZ_PTO_EMPLOYEES" USING 'ZZ_PTO_EMPLOYEES.mkd' PAGESIZE=4096 (
 "EMPLOYEE" CHAR(5),
 "NAME" CHAR(100),
 "AVAILABLE" DOUBLE,
 "SUP_ID" CHAR(5),
 "SUPERVSR" CHAR(100),
 "PAY_TYPE" CHAR(1),
 "HIRE_DATE" DATE,
 "PTO_STEP_DATE" DATE,
 "PTO_STEP" INTEGER,
 "SHIFT_HOURS" DOUBLE DEFAULT '8' );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
