-- Database: GLOBALVSF Metadata version: 2 Exported: Jan 31, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "ZZ_PTO_ACC_HIST" USING 'ZZ_PTO_ACC_HIST.mkd' PAGESIZE=4096 (
 "EMPLOYEE" CHAR(5),
 "PREVIOUS_PTO" DOUBLE,
 "NEW_PTO" DOUBLE,
 "PREVIOUS_STEP" DOUBLE,
 "NEW_STEP" DOUBLE,
 "DATE_CHANGED" DATE,
 "UNIQID" CHAR(16),
 "HOURS_WORKED" DOUBLE );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
