-- Database: GLOBALVSF Metadata version: 2 Exported: Jan 31, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "ZZ_PTO_CASH_OUT" USING 'ZZ_PTO_CASH_OUT.mkd' PAGESIZE=4096 (
 "EMPLOYEE" CHAR(5) NOT NULL,
 "NAME" CHAR(50) NOT NULL,
 "DATE" DATE NOT NULL,
 "AMOUNT" DOUBLE NOT NULL );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
