-- Database: GLOBALVSF Metadata version: 2 Exported: Jan 31, 2022
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "ZZ_PTO_TAQ" USING 'ZZ_PTO_TAQ.mkd' PAGESIZE=4096 (
 "EMPLOYEE" CHAR(5),
 "CHARGE_DATE" NUMERIC(8,0),
 "DATE_IN" CHAR(8),
 "DATE_OUT" CHAR(8),
 "NAME" CHAR(30),
 "DEPT" CHAR(4),
 "SHIFT" CHAR(1),
 "REC_GROUP" CHAR(8),
 "REC_TYPE" CHAR(1),
 "EARNINGS_CODE" CHAR(2),
 "PAID" CHAR(1),
 "EXCUSED" CHAR(1),
 "BAL_AS_DATE" CHAR(8),
 "DATE_LAST_CHG" CHAR(8),
 "TIME_LAST_CHG" CHAR(8),
 "LAST_CHG_BY" CHAR(8),
 "LAST_CHG_PROG" CHAR(8),
 "HOURS_HH" NUMERIC(2,0),
 "HOURS_MM" NUMERIC(2,0),
 "DOLLAR_AMT" NUMERIC(10,2),
 "ACTUAL_DATE" DATE,
 "PAYROLL_LOCK" BIT NOT NULL );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
